### ISSUE TITLE
Set blog homepage

### ISSUE THREAD

**Issue by DursunCanPoyraz** [v17development/flarum-blog#53]
Flarum logs:

```
[2021-01-22 10:03:52] flarum.ERROR: Exception: V17Development\FlarumSeo\Extend::setTitle(..): Container was not yet initialized. in /home/oyundede/beta15.quzz.net/vendor/v17development/flarum-seo/src/Extend.php:196
Stack trace:
#0 /home/oyundede/beta15.quzz.net/vendor/v17development/flarum-seo/src/Extend.php(36): V17Development\FlarumSeo\Extend::throwError('setTitle')
#1 /home/oyundede/beta15.quzz.net/vendor/v17development/flarum-blog/src/Controller/BlogOverviewController.php(30): V17Development\FlarumSeo\Extend::setTitle('Blog')
#2 /home/oyundede/beta15.quzz.net/vendor/flarum/core/src/Frontend/Frontend.php(63): V17Development\FlarumBlog\Controller\BlogOverviewController->__invoke(Object(Flarum\Frontend\Document), Object(Laminas\Diactoros\ServerRequest))
#3 /home/oyundede/beta15.quzz.net/vendor/flarum/core/src/Frontend/Frontend.php(55): Flarum\Frontend\Frontend->populate(Object(Flarum\Frontend\Document), Object(Laminas\Diactoros\ServerRequest))
#4 /home/oyundede/beta15.quzz.net/vendor/flarum/core/src/Frontend/Controller.php(32): Flarum\Frontend\Frontend->document(Object(Laminas\Diactoros\ServerRequest))
#5 /home/oyundede/beta15.quzz.net/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): Flarum\Frontend\Controller->handle(Object(Laminas\Diactoros\ServerRequest))
#6 /home/oyundede/beta15.quzz.net/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}(Object(Laminas\Diactoros\ServerRequest), Array)
#7 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ExecuteRoute->process(Object(Laminas\Diactoros\ServerRequest), Object(Closure))
#8 /home/oyundede/beta15.quzz.net/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php(57): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#9 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ShareErrorsFromSession->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#10 /home/oyundede/beta15.quzz.net/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(40): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#11 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\CheckCsrfToken->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#12 /home/oyundede/beta15.quzz.net/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(67): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#13 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ResolveRoute->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#14 /home/oyundede/beta15.quzz.net/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#15 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\SetLocale->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#16 /home/oyundede/beta15.quzz.net/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#17 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithSession->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#18 /home/oyundede/beta15.quzz.net/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(51): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#19 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\RememberFromCookie->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#20 /home/oyundede/beta15.quzz.net/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#21 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\StartSession->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#22 /home/oyundede/beta15.quzz.net/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php(46): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#23 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\CollectGarbage->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#24 /home/oyundede/beta15.quzz.net/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#25 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ParseJsonBody->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#26 /home/oyundede/beta15.quzz.net/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#27 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\HandleErrors->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#28 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#29 /home/oyundede/beta15.quzz.net/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#30 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\RequestHandler->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#31 /home/oyundede/beta15.quzz.net/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#32 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePathRouter->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#33 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(42): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#34 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\OriginalMessages->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#35 /home/oyundede/beta15.quzz.net/vendor/middlewares/base-path/src/BasePath.php(53): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#36 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePath->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#37 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#38 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\EmptyPipelineHandler))
#39 /home/oyundede/beta15.quzz.net/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle(Object(Laminas\Diactoros\ServerRequest))
#40 /home/oyundede/beta15.quzz.net/vendor/flarum/core/src/Http/Server.php(42): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#41 /home/oyundede/beta15.quzz.net/index.php(26): Flarum\Http\Server->listen()
#42 {main}  
```

![image](https://user-images.githubusercontent.com/74768208/105476814-1fa87580-5cb2-11eb-98b5-e3cc28582967.png)

![image](https://user-images.githubusercontent.com/74768208/105476744-0c95a580-5cb2-11eb-9140-8ad74432893e.png)

![image](https://user-images.githubusercontent.com/74768208/105476768-115a5980-5cb2-11eb-9ed6-d2ff32b9f36e.png)

**Comment by jaspervriends** [comment]
This is an issue with the SEO extension, we'll make sure to fix this soon!

**Comment by arthuragone** [comment]
I have a similar issue and no SEO extension activated

**Comment by arthuragone** [comment]
It this issue realy resolved ?

**Comment by CWKevo** [comment]
This error just happened at my forum, because the Blog extension utilizes some property from SEO extension(?). Well, enabling SEO will make Blog work (at least at my forum). This is why not having SEO enabled actually causes this issue. So no, this is not yet resolved.

I suggest you to mark SEO as dependency, so Blog can't be enabled before enabling SEO and forum doesn't crash. Or, make Blog independent to SEO.
